spring.application.name=auth-service
server.port=8093

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/sigip_auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

sigip.jwt.secret=${JWT_SECRET}
sigip.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:30}

sigip.admin.username=${SIGIP_ADMIN_USERNAME:admin}
sigip.admin.email=${SIGIP_ADMIN_EMAIL:admin@sigip.local}
sigip.admin.password=${SIGIP_ADMIN_PASSWORD:}
