spring.application.name=report-service
server.port=8100
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
sigip.jwt.secret=${JWT_SECRET}
management.endpoints.web.exposure.include=health,info