spring.application.name=api-gateway
server.port=8090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8093
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth-service/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[1].id=catalog-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8094
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/catalog-service/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1
