spring.application.name=api-gateway
server.port=8090
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8093
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth-service/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[1].id=catalog-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8094
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/catalog-service/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[2].id=sales-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8095
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/sales-service/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[3].id=design-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8096
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/design-service/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[4].id=production-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8097
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/production-service/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[5].id=inventory-service
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8098
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/inventory-service/**
spring.cloud.gateway.server.webflux.routes[5].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[6].id=notification-service
spring.cloud.gateway.server.webflux.routes[6].uri=http://localhost:8099
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/notification-service/**
spring.cloud.gateway.server.webflux.routes[6].filters[0]=StripPrefix=1
spring.cloud.gateway.server.webflux.routes[7].id=report-service
spring.cloud.gateway.server.webflux.routes[7].uri=http://localhost:8100
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/report-service/**
spring.cloud.gateway.server.webflux.routes[7].filters[0]=StripPrefix=1